In [0]:
import numpy as np

In [0]:
def initialize_population( num_individuals, num_variables ):
    """
    Khởi tạo quần thể gồm num_individuals cá thể. Mỗi cá thể có num_parameters biến.
    
    Arguments:
    num_individuals -- Số lượng cá thể
    num_variables -- Số lượng biến
    
    Returns:
    pop -- Ma trận (num_individuals, num_variables) chứa quần thể mới được khởi tạo ngẫu nhiên.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    pop = np.random.randint(2, size=(num_individuals, num_variables))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return pop

In [0]:
def onemax( ind ):
    """
    Hàm đánh giá OneMax: Đếm số bit 1 trong chuỗi nhị phân (cá thể ind).
    
    Arguments:
    ind -- Cá thể cần được đánh giá.

    Returns:
    value -- Giá trị của cá thể ind.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ###     
    value = np.sum(ind)
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return value

In [0]:
def trapone(ind, k):
    value = 0
    u = np.sum(ind)
    if u < k:
        value = k - 1 - u
    elif u == k:
        value = u
        
    return value

In [0]:
print(trapone([1, 0, 1, 1, 0], 5))

1


In [0]:
def evaluate_population( pop ):
    """
    Hàm đánh giá tất cả cá thể trong quần thể.
    
    Arguments:
    pop -- Quàn thể cần được đánh giá.

    Returns:
    values -- Giá trị của tất cả các cá thể trong quần thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    values = list(map(onemax, pop))
    
    ### DỪNG CODE TẠI ĐÂY ###
    
    return values

In [0]:
p = initialize_population(4, 8)
print(p)
print(evaluate_population(p))

[[0 0 0 0 1 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 1 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 0]]
[1, 4, 3, 1]


In [0]:
print((evaluate_population(p)))

[2]


In [0]:
def better_fitness( fitness_1, fitness_2, maximization=True ):
    """
    Hàm so sánh độ thích nghi của 2 cá thể.
    
    Arguments:
    fitness_1 -- Độ thích nghi của cá thể 1.
    fitness_2 -- Độ thích nghi của cá thể 2.
    maximization -- Biến boolean cho biết bài toán đang giải thuộc dạng tối đa hoá (mặc định) hay không
    
    Returns:
    True nếu fitness_1 tốt hơn fitness_2. Ngược lại, trả về False.
    """
    
    if maximization:
        if fitness_1 > fitness_2:
            return True
    else:
        if fitness_1 < fitness_2:
            return True
        
    return False

In [0]:
def tournament_selection( pop, pop_fitness, selection_size, tournament_size = 4):
    """
    Hàm chọn lọc cạnh tranh.
    
    Arguments:
    pop -- Quần thể để thực hiện phép chọn lọc.
    pop_fitness -- Mảng 1 chiều chứa giá trị (độ thích nghi) của từng cá thể trong quần thể.
    selection_size -- Số lượng cá thể sẽ được chọn.
    tournament_size -- Kích thước của tournament: Số lượng các cá thể được so sánh với nhau mỗi lần.
    
    Returns:
    selected_indices -- Chỉ số của những cá thể trong quần thể pop được chọn. Chỉ số có thể được lặp lại.
    """
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    indices = np.array(range(num_individuals))
    selected_indices = []
    
    while len(selected_indices) < selection_size:
        # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể.
        np.random.shuffle(indices)
        for i in range(0, num_individuals, tournament_size):
            max = pop_fitness[indices[i]]
            max_i = indices[i]
            tournament_range = indices[i: i + tournament_size]
            for j in tournament_range:
                if pop_fitness[j] > max:
                    max = pop_fitness[j]
                    max_i = j
            selected_indices.append(max_i)
        
    ### DỪNG CODE TẠI ĐÂY ###
    
    return selected_indices

In [0]:
pop = initialize_population(8,12)
print(pop)
pop_fitness = evaluate_population(pop)
print(pop_fitness)
print(tournament_selection(pop,pop_fitness, 4, 4))

[[1 0 1 1 0 0 1 1 0 1 0 1]
 [0 1 1 0 0 1 0 0 0 0 0 1]
 [1 0 0 1 1 1 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 0 0 0 1 0]
 [0 1 1 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 0 0 1 1 0 1 1 1]
 [1 0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 1 0 1 1 0 1 0 1]]
[7, 4, 7, 4, 7, 8, 3, 6]
[0, 5, 5, 2]


In [0]:
def variation( pop ):
    """
    Hàm biến đổi tạo ra các cá thể con.
    
    Arguments:
    pop -- Quàn thể hiện tại.

    Returns:
    offspring -- Quần thể chứa các cá thể con được sinh ra.
    """  
    
    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    num_individuals = len(pop)
    num_parameters = len(pop[0])
    indices = np.array(range(num_individuals))
    # Đảo ngẫu nhiên thứ tự các cá thể trong quần thể
    np.random.shuffle(indices)
    offspring = []
    
    for i in range(0, num_individuals, 2):
        idx1 = indices[i]
        idx2 = indices[i+1]
        offspring1 = list(pop[idx1])
        offspring2 = list(pop[idx2])
        
        # Cài đặt phép lai đồng nhất uniform crossover. 
        # Không cần cài đặt đột biến mutation.
        random_arr = np.random.rand(1, num_parameters)
        
        for j in range(num_parameters):
            if random_arr[0][j] < 0.5:
                temp = offspring1[j]
                offspring1[j] = offspring2[j]
                offspring2[j] = temp

        offspring.append(offspring1)
        offspring.append(offspring2)


    ### DỪNG CODE TẠI ĐÂY ###
    
    offspring = np.array(offspring)
    return offspring

In [0]:
pop = initialize_population(8,12)
print(pop)
print(variation(pop))

In [0]:
def propability (pop):
    p_arr = []
    
    num_invidiuals = len(pop)
    num_para = len(pop[0])
    for j in range(num_para): 
        sum = 0
        for i in range(num_invidiuals):
            sum += pop[i][j]
        p_arr.append(sum / num_invidiuals)
    
    return p_arr

In [0]:
pop = initialize_population(8,12)
print(pop)
print(propability(pop))

In [0]:
def generate ( model ):
    new_model = []
    num_variables = len(model)
    random_arr = np.random.rand(1, num_variables)
    for i in range(num_variables):
        if ((random_arr[0, i]) <= (model[i])):
            new_model.append(1)
        else:
            new_model.append(0)
    return new_model

In [0]:
pop = initialize_population(8,12)
print(pop)
p = propability(pop)
print(generate(p))

In [0]:
def generate_new_pop(pop, num):
    new_pop = []
    for i in range(num):
        new_pop.append(generate(pop))
    new_pop = np.array(new_pop)
    return new_pop

In [0]:
pop = initialize_population(8,12)
print(pop)
p = propability(pop)
print(generate_new_pop(p, 4))

In [0]:
def popop(num_individuals, num_parameters, num_generations):
    """
    Hàm cài đặt thuật giải di truyền theo các bước P->O->(P+O)->P
    
    Arguments:
    num_individuals -- Số lượng cá thể trong quần thể.
    num_parameters -- Số lượng biến.
    num_generations -- Số thế hệ thuật toán sẽ chạy.

    Returns:
    In ra quần thể ở thế hệ cuối cùng và giá trị của từng cá thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    # Khởi tạo quần thể
    pop = initialize_population(num_individuals,num_parameters)
    pop_fitness = evaluate_population(pop)
    print("#Gen 0:")
    print(pop_fitness)
    
    # Sử dụng tournament_size 4 và selection_size là bằng kích thước quần thể
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):
        # Tạo ra các cá thể con và đánh giá chúng
        offspring = variation(pop)
        offspring_fitness = evaluate_population(offspring)
        
        # Tạo ra quần thể pool gồm quần thể hiện tại pop và offspring
        pool = np.vstack((pop,offspring))
        pool_fitness = np.hstack((pop_fitness, offspring_fitness))

        # Thực hiện tournament selection trên quần thể pool 
        pool_indices = tournament_selection(pool,pool_fitness,selection_size,tournament_size)

        # Thay thế quần thể hiện tại bằng những cá thể được chọn ra từ pool.
        pop = pool[pool_indices, :]
        pop_fitness = pool_fitness[pool_indices]
        print("#Gen {}:".format(i+1))
        print(pop_fitness)

    ### DỪNG CODE TẠI ĐÂY ###
    print("#Result:")
    print(pop)
    print(pop_fitness)

In [0]:
def umda_popop(num_individuals, num_parameters, num_generations):
    """
    Hàm cài đặt thuật giải di truyền theo các bước P->O->(P+O)->P
    
    Arguments:
    num_individuals -- Số lượng cá thể trong quần thể.
    num_parameters -- Số lượng biến.
    num_generations -- Số thế hệ thuật toán sẽ chạy.

    Returns:
    In ra quần thể ở thế hệ cuối cùng và giá trị của từng cá thể.
    """ 

    ### BẮT ĐẦU CODE TỪ ĐÂY ### 
    # Khởi tạo quần thể
    pop = initialize_population(num_individuals,num_parameters)
    pop_fitness = evaluate_population(pop)
    print("#Gen 0:")
    print(pop_fitness)
    
    # Sử dụng tournament_size 4 và selection_size là bằng kích thước quần thể
    selection_size = len(pop)
    tournament_size = 4

    for i in range(num_generations):
        # Tạo ra các cá thể con và đánh giá chúng
        p = propability(pop)
        offspring = generate_new_pop(p, num_individuals)
        offspring_fitness = evaluate_population(offspring)
        
        # Tạo ra quần thể pool gồm quần thể hiện tại pop và offspring
        pool = np.vstack((pop,offspring))
        pool_fitness = np.hstack((pop_fitness, offspring_fitness))

        # Thực hiện tournament selection trên quần thể pool 
        pool_indices = tournament_selection(pool,pool_fitness,selection_size,tournament_size)

        # Thay thế quần thể hiện tại bằng những cá thể được chọn ra từ pool.
        pop = pool[pool_indices, :]
        pop_fitness = pool_fitness[pool_indices]
        print("#Gen {}:".format(i+1))
        print(pop_fitness)

    
    ### DỪNG CODE TẠI ĐÂY ###
    print("#Result:")
    print(pop)
    print(pop_fitness)